### ISSUE TITLE
Problème avec des lat/lon négatives

### ISSUE THREAD

**Issue by rhaamo** [f4iha/arduino-ft4x-aprs-tracker#1]
Après debug avec un autre radioamateur, qui se trouve avoir une LNG négative, on a du changer la ligne suivante:
https://github.com/f4iha/arduino-ft4x-aprs-tracker/blob/main/src/APRS.cpp#L181

en:
```
stringPaddingf(fabsf(lngDegMin), 5, &packetBuffer);
```

`fabsf` seulement a l'insertion pour passer en positif.

Dans son cas ça fonctionne.

Je soupçonne qu'il faille faire pareil pour la LAT a la ligne 169

**Comment by f4iha** [comment]
Merci @rhaamo pour le retour.
Je viens de modifier le code. Impossible d'avoir une situation réelle pour moi donc je me base sur le retour.
J'ai aussi remarqué une valeur incorrecte pour la latitude à la ligne 174 https://github.com/f4iha/arduino-ft4x-aprs-tracker/commit/885183f50143717b1980dde922449a3f40805ddc

Si aucun autre changement n'a été effectué, je fusionnerais la PR avec les changements
